ex2-segmentation: ex2-segmentation.cpp
	g++ -I../../include -I../include -o ex2-segmentation ex2-segmentation.cpp

ex2-colors: ex2-colors.cpp
	g++ -I../../include -I../include -o ex2-colors ex2-colors.cpp
	
clean:
	rm -f ex2-segmentation ex2-colors

